### ISSUE TITLE
Does the weight file support exporting onnx?

### ISSUE THREAD

**Issue by acai22** [longzw1997/Open-GroundingDino#1]
Without modifying the model source code.

**Comment by longzw1997** [comment]
You can consider using torch.onnx.export for conversion.

**Comment by HeChengHui** [comment]
@longzw1997 @BIGBALLON 

I am trying to export to onnx and having troubles with the **kw in the [forward](https://github.com/longzw1997/Open-GroundingDino/blob/a1f9128db6f6fee00c0552aab0a1d381d834dbe3/models/GroundingDINO/groundingdino.py#L216) function.

```
input = (image[None], {"caption":[caption]})
torch.onnx.export(model, input, "gdinot-1.8m-odvg.onnx", input_names=["samples", "kw"], output_names=["pred_logits", "pred_boxes"])
```
It keep is not passing the dict into **kw. I have also tried passing the caption using the targets argument but it also generated another error. 
Please advice.

**Comment by Zeyuma885** [comment]
> Without modifying the model source code.

可以参考你的torch.onnx.export如何设置吗，我遇到了这个问题RuntimeError: _Map_base::at。

**Comment by yu1206** [comment]
result = self.forward(*input, **kwargs)
TypeError: forward() takes from 2 to 3 positional arguments but 9 were given
出现这个错误
