### ISSUE TITLE
Why I still can't pass test.py test when I use 80GB A100, it will still explode memory.

### ISSUE THREAD

**Issue by lanhas** [longzw1997/Open-GroundingDino#11]
This GPU does not run any programs
![image](https://github.com/longzw1997/Open-GroundingDino/assets/38825678/560a0855-5ef7-432c-bccc-393c399a959e)

**Comment by BIGBALLON** [comment]
- please check this issue https://github.com/longzw1997/Open-GroundingDino/issues/7 
- This PR fixed this issue https://github.com/longzw1997/Open-GroundingDino/pull/10

**Comment by BIGBALLON** [comment]
Hi, @lanhas is your model training running normally? I would like to know the current status of the latest code.

**Comment by lanhas** [comment]
Hello， @BIGBALLON Thank you very much for your work! The current code works fine, and it successfully trains on our small dataset. Of course, this is just a running test, without evaluation. I will contact you in time if there are any questions during the follow-up training.

The environment information is pytorch2.1.0-cuda12.1, node=1, gpus=8.
