### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by nicholasprimiano** [longzw1997/Open-GroundingDino#12]
The latest version fixes the cuda issue but produces the following Traceback. It looks like the label_map is not being moved the GPU. To fine tune on coco, I created a new json file with the label map as described in the data_format.md file.

`
Traceback (most recent call last):
  File "/content/Open-GroundingDino/main.py", line 372, in <module>
    main(args)
  File "/content/Open-GroundingDino/main.py", line 285, in main
    train_stats = train_one_epoch(
  File "/content/Open-GroundingDino/engine.py", line 48, in train_one_epoch
    loss_dict = criterion(outputs, targets, cap_list, captions)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/Open-GroundingDino/models/GroundingDINO/groundingdino.py", line 553, in forward
    inds = self.matcher(for_match, [targets[j]], label_map_list[j])
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Open-GroundingDino/models/GroundingDINO/matcher.py", line 80, in forward
    new_label_map=label_map[tgt_ids]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
`

I changed datasets_od_example.json as follow:

`
{
  "train": [
    {
      "root": "/content/dataset_folder/train2017",
      "anno": "/content/drive/MyDrive/coco/annotations/instances_train2017.jsonl",
      "label_map": "/content/drive/MyDrive/coco/coco2017_label_map.json",
      "dataset_mode": "odvg"
    }
  ],
  "val": [
    {
      "root": "/content/dataset_folder/val2017",
      "anno": "/content/dataset_folder/annotations/instances_val2017.json",
      "label_map": null,
      "dataset_mode": "coco"
    }
  ]
}`

**Comment by lanhas** [comment]
Same problem

**Comment by longzw1997** [comment]
Did you use distributed torch.distributed.launch when starting the code?

**Comment by BIGBALLON** [comment]
Hi, @nicholasprimiano @lanhas 

- We tested the code on CUDA 11.3 and PyTorch 1.12.1 (with Python 3.8.18) and **it worked well**.
- Then reteset on  CUDA-11.8 and pytorch 2.1.0(with Python 3.10.13), reproduced your issue:

``` bash
# pdb debug log
-> new_label_map=label_map[tgt_ids]
(Pdb) tgt_ids
tensor([45, 45, 75], device='cuda:0')
(Pdb) label_map
tensor([[0., 1., 1.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
(Pdb) tgt_ids.cpu()
tensor([45, 45, 75])
```

this [PR](https://github.com/longzw1997/Open-GroundingDino/pull/14) fixed the issue by moving tensor to right device. 

``` diff
-        tgt_ids = [v["labels"] for v in targets]
+        tgt_ids = [v["labels"].cpu() for v in targets]
```

``` diff
        alpha = self.focal_alpha
        gamma = 2.0

-       new_label_map=label_map[tgt_ids]
+       new_label_map=label_map[tgt_ids.cpu()]

        neg_cost_class = (1 - alpha) * (out_prob ** gamma) * (-(1 - out_prob + 1e-8).log())
        pos_cost_class = alpha * ((1 - out_prob) ** gamma) * (-(out_prob + 1e-8).log())
```

**Comment by lanhas** [comment]
> Hi, @nicholasprimiano @lanhas
> 
> * We tested the code on **CUDA 11.3 and PyTorch 1.12.1 (with Python 3.8.18)** and **it worked well**.
> * Then reteset on  CUDA-11.8 and pytorch 2.1.0(with Python 3.10.13), reproduced your issue:
> 
> ```shell
> # pdb debug log
> -> new_label_map=label_map[tgt_ids]
> (Pdb) tgt_ids
> tensor([45, 45, 75], device='cuda:0')
> (Pdb) label_map
> tensor([[0., 1., 1.,  ..., 0., 0., 0.],
>         [0., 0., 0.,  ..., 0., 0., 0.],
>         [0., 0., 0.,  ..., 0., 0., 0.],
>         ...,
>         [0., 0., 0.,  ..., 0., 0., 0.],
>         [0., 0., 0.,  ..., 0., 0., 0.],
>         [0., 0., 0.,  ..., 0., 0., 0.]])
> (Pdb) tgt_ids.cpu()
> tensor([45, 45, 75])
> ```
> 
> this [PR](https://github.com/longzw1997/Open-GroundingDino/pull/14) fixed the issue by moving tensor to right device.
> 
> ```diff
> -        tgt_ids = [v["labels"] for v in targets]
> +        tgt_ids = [v["labels"].cpu() for v in targets]
> ```
> 
> ```diff
>         alpha = self.focal_alpha
>         gamma = 2.0
> 
> -       new_label_map=label_map[tgt_ids]
> +       new_label_map=label_map[tgt_ids.cpu()]
> 
>         neg_cost_class = (1 - alpha) * (out_prob ** gamma) * (-(1 - out_prob + 1e-8).log())
>         pos_cost_class = alpha * ((1 - out_prob) ** gamma) * (-(out_prob + 1e-8).log())
> ```

Thanks, this works fine in pytorch 2.1.0.
