### ISSUE TITLE
device spec for training and finetuning

### ISSUE THREAD

**Issue by sherlock666** [longzw1997/Open-GroundingDino#2]
May I ask the device spec for training and finetuning?
RAM, GPU

and how long does it take for the data you use 

thanks!!

**Comment by longzw1997** [comment]
Pre-training used 32 NVIDIA V100 32GB GPUs, with an average time of 16 hours per epoch. Fine-tuning on COCO used 16 NVIDIA V100 32GB GPUs, with an average time of 2.5 hours per epoch.

**Comment by wangshuang-jiayou** [comment]
> Pre-training used 32 NVIDIA V100 32GB GPUs, with an average time of 16 hours per epoch. Fine-tuning on COCO used 16 NVIDIA V100 32GB GPUs, with an average time of 2.5 hours per epoch.
您好，我自己也复现过一版finetune代码，在自己的数据集上finetune以后在自己的数据集上有53%的map，该模型再次在coco上eval只有3%的map，似乎finetune破坏了pretrain的模型特征。我现在是冻结了bert，没有冻结backbone.0也就是visiual backbone。请问你有什么建议嘛？对于finetune

**Comment by BIGBALLON** [comment]
Hi. @wangshuang-jiayou

- For fintune: choose a reasonable steps(epochs) to get good downstream task performance but avoid overfitting
- For model generalization: you can use model ensemble tech such as [WISE-FT](https://github.com/mlfoundations/wise-ft) to balacne the weights of finetune model and pretrain Model. 
    - [OWL-V2](https://github.com/google-research/scenic/tree/main/scenic/projects/owl_vit) is also used this model ensemble trick.

**Comment by wangshuang-jiayou** [comment]
> Hi. @wangshuang-jiayou
> 
> * **For fintune**: choose a reasonable steps(epochs) to get good downstream task performance but avoid overfitting (depends on dataset itself)
> * **For generalization**: you can use model **ensemble** tech such as [WISE-FT](https://github.com/mlfoundations/wise-ft) to balacne the weights of finetune model and pretrain model.
>   
>   * [OWL-V2](https://github.com/google-research/scenic/tree/main/scenic/projects/owl_vit)  (which is the strongest OVD model now) is also used this model ensemble tr thank you!!!!!!!!!!!!!!!!!!!!!!!

> Hi. @wangshuang-jiayou
> 
> * **For fintune**: choose a reasonable steps(epochs) to get good downstream task performance but avoid overfitting (depends on dataset itself)
> * **For generalization**: you can use model **ensemble** tech such as [WISE-FT](https://github.com/mlfoundations/wise-ft) to balacne the weights of finetune model and pretrain model.
>   
>   * [OWL-V2](https://github.com/google-research/scenic/tree/main/scenic/projects/owl_vit)  (which is the strongest OVD model now) is also used this model ensemble trick.

thank you sosoosososo much!
