### ISSUE TITLE
UnpicklingError: invalid load key, '<'.  unable to use new trained weights for taking detections or inferencing

### ISSUE THREAD

**Issue by Pratik-Ghute** [longzw1997/Open-GroundingDino#21]
**Open-GroundingDino (this repo) didnt seem to have modules for inferencing on new trained weights(.pth).** 

I tried using IDEA-Research/GroundingDINO (official implementation) repo for taking detections by providing path of newly trained weights which gave me error like:

UnpicklingError                           Traceback (most recent call last)
<ipython-input-15-6045da8a57a6> in <cell line: 6>()
      4 import time
      5 
**----> 6 model = load_model("/content/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py", "/content/GroundingDINO/weights/groundingdino_swint_ogc.pth")**

2 frames
/usr/local/lib/python3.10/dist-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
   1244             "functionality.")
   1245 
-> 1246     magic_number = pickle_module.load(f, **pickle_load_args)
   1247     if magic_number != MAGIC_NUMBER:
   1248         raise RuntimeError("Invalid magic number; corrupt file?")

**UnpicklingError: invalid load key, '<'.**

**Also I need clarity on multiple weights file getting generated i understood there is a weight file for each epoch and a file named "checkpoint_best_regular.pth" is it weight file for epoch with lowest "loss" or highest accuracy?   and also eval folder has 2 weight files latest.pth and 000.pth?  what are those for?**

**Comment by Pratik-Ghute** [comment]
issue is resolved it was error due to wieght file exceeding 1gb, thanks

**Comment by BIGBALLON** [comment]
Because the model architecture has not changed, you only need to **install** [GroundingDINO](https://github.com/IDEA-Research/GroundingDINO) library and then run [inference_on_a_image.py](/Users/bigballon/Downloads/Open-GroundingDino/tools/inference_on_a_image.py) to inference your images.

``` bash
python tools/inference_on_a_image.py \
  -c tools/GroundingDINO_SwinT_OGC.py \
  -p path/to/your/ckpt.pth \
  -i ./figs/dog.jpeg \
  -t "dog" \
  -o output
```

**Comment by Pratik-Ghute** [comment]
thanks, could you please tell me the this training pipeline is finetuning pretrained swinT weights or training from scratch?

**Comment by BIGBALLON** [comment]
@Pratik-Ghute  pretrain or finetune are OK. Using finetune can save some costs, but if you can obtain more and higher quality data, you can train the model from scratch for higher performance.
