### ISSUE TITLE
How to create your own dataset and use it to tune the model

### ISSUE THREAD

**Issue by zy199676** [longzw1997/Open-GroundingDino#22]
May I ask how I can create a dataset for my own data to tune? I am currently working on tasks related to driving area detection and would like to use the weights in the Grounded-SAM model after tuning. Thank you.

**Comment by BIGBALLON** [comment]
For training, we use the [odvg data format](https://github.com/longzw1997/Open-GroundingDino/blob/main/data_format.md) to support both OD data and VG data.
Before model training begins, you need to convert your dataset into odvg format, see [data_format.md](https://github.com/longzw1997/Open-GroundingDino/blob/main/data_format.md) | [datasets_mixed_odvg.json](https://github.com/longzw1997/Open-GroundingDino/blob/main/config/datasets_mixed_odvg.json) | [coco2odvg.py](https://github.com/longzw1997/Open-GroundingDino/blob/main/tools/coco2odvg.py) | [grit2odvg](https://github.com/longzw1997/Open-GroundingDino/blob/main/tools/grit2odvg.py) for more details.

For testing, we use [coco format](https://cocodataset.org/#format-data), which currently only supports OD datasets.

**Comment by zfr00** [comment]
sorry to ask can you supports the VG datasets now?

**Comment by BIGBALLON** [comment]
> sorry to ask can you supports the VG datasets now?

Sorry, we currently lack the bandwidth to support additional reviews and do not have plans to extend our support. If you find the time, you are welcome to submit a pull request to introduce this feature.
