### ISSUE TITLE
Where is the DN module in the training code？

### ISSUE THREAD

**Issue by Baboom-l** [longzw1997/Open-GroundingDino#26]
I couldn't find the denoising training module, like the one used in DINO

**Comment by longzw1997** [comment]
The DN module is not used in this code.

**Comment by tea1528** [comment]
Is there any reason why there's no DN module? Did you face any overfitting during odvg pretraining?

**Comment by BIGBALLON** [comment]
@tea1528 
I'm not sure DN module is useful or not, but you can try to add it.  
According to GLIP, semantic-rich dataset is the key for **pretrain**.


For fintune: Using finetune can save some costs, but if you can obtain more and higher quality data, you can train the model from scratch for higher performance. choose a reasonable steps(epochs) to get good downstream task performance but avoid overfitting (depends on dataset itself), you can use model ensemble tech such as [WISE-FT](https://github.com/mlfoundations/wise-ft) to balacne the weights of finetune model and pretrain model.
[OWL-V2](https://github.com/google-research/scenic/tree/main/scenic/projects/owl_vit) (which is the strongest OVD model now) is also used this model ensemble trick.
