### ISSUE TITLE
In /tools/inference_on_a_image.py, is there a difference between IDEA-Research's code and longzw1997's code?

### ISSUE THREAD

**Issue by ImcwjHere** [longzw1997/Open-GroundingDino#27]
Some functions call the code here:
https://github.com/longzw1997/Open-GroundingDino/
Others call the code here:
https://github.com/IDEA-Research/GroundingDINO/

Directory Structure (I moved it ro the root directory)
![image](https://github.com/longzw1997/Open-GroundingDino/assets/17983189/b7de872c-28ef-4a7a-897b-3c764539c373)

```
# These calls IDEA-Research's code
import groundingdino.datasets.transforms as T
from groundingdino.models import build_model
# These calls longzw1997's code
from groundingdino.util import box_ops
from groundingdino.util.slconfig import SLConfig
from groundingdino.util.utils import clean_state_dict, get_phrases_from_posmap
from groundingdino.util.vl_utils import create_positive_map_from_span
```

In this code, it works normally. However, when I uninstalled rf-groundingdino (IDEA-Research's code) and tried to making this code use longzw1997's code as follows:

```
import datasets.transforms as T
from models import build_model_inference
from groundingdino.util import box_ops
from groundingdino.util.slconfig import SLConfig
from groundingdino.util.utils import clean_state_dict, get_phrases_from_posmap
from groundingdino.util.vl_utils import create_positive_map_from_span
```

It raised AttributeError: 'ConfigDict' object has no attribute 'coco_val_path'.

Of course, I see that comment about installing IDEA-Research. But I'm little confused, is there a difference between these two codes?

**Comment by BIGBALLON** [comment]
@ImcwjHere There is no difference between the two scripts. They are just copied to our project and some minor bugs are fixed.

**Comment by ImcwjHere** [comment]
> @ImcwjHere There is no difference between the two scripts. They are just copied to our project and some minor bugs are fixed. (So you can use either of the two scripts)

I found that IDEA-Research's code just builds a model, but longzw1997 has more code for training the model, thus raising some errors. The problem has been resolved, thanks for your reply!

**Comment by BIGBALLON** [comment]
@ImcwjHere sounds good!  👍
