### ISSUE TITLE
Errors of distributed training

### ISSUE THREAD

**Issue by Jordanyang** [longzw1997/Open-GroundingDino#28]
你好，使用你推荐的配置文件，使用coco数据集进行微调，发现不能进行分布式训练，使用的配置文件为：cfg_odvg.py，分布式训练截图如下：
![image](https://github.com/longzw1997/Open-GroundingDino/assets/12427197/2ff2abdb-fdac-4ccd-be81-f54c43751641)

**Comment by BIGBALLON** [comment]
Can you show more logs(env, package version, etc.)?
Is the inference work fine?

**Comment by Jordanyang** [comment]
1：你好，相关环境为：python3.8.10,  pytorch1.9 ,CUDA12.0,当我在配置文件中将freeze_keywords = []时， 可以正常进行分布式训练，但冻住bert层时freeze_keywords = [‘bert’],多GPU分布式训练失败；
2：inference work is fine

**Comment by BIGBALLON** [comment]
- [datasets_od_example.json](https://github.com/longzw1997/Open-GroundingDino/files/13246679/datasets_od_example.json)
- [config_cfg.py](https://github.com/longzw1997/Open-GroundingDino/files/13246680/config_cfg.txt)

Pytorch1.9 may be too old, can you change it to the version >=1.11.0 ?
