### ISSUE TITLE
Simple questions regarding fine-tuning the model on custom data.

### ISSUE THREAD

**Issue by Leebh-kor** [longzw1997/Open-GroundingDino#29]
Hi, i would like to express my infinite gratitude for sharing the training code of GroundingDINO 🙌.

I want to fine-tune the model using gdinot-1.8m-odvg.pth on a custom dataset. Could you provide some advice on how to set the freeze layer?

Alternatively, if it's not too much trouble, could you let me know which layers were frozen during the fine-tuning of your GroundingDINO-T(fine-tune)?

Thank you!

**Comment by BIGBALLON** [comment]
We fixed the BERT backbone weight, you can also freeze the visual backbone. e.g. ['backbone.0', 'bert'] for freeze visual encoder and text encoder

https://github.com/longzw1997/Open-GroundingDino/blob/33010c4c4d359f1e5896d609a0ba5fc73e376bbc/config/cfg_odvg.py#L48-L53
