### ISSUE TITLE
Questions regarding fine-tuning the model on custom data.

### ISSUE THREAD

**Issue by Leebh-kor** [longzw1997/Open-GroundingDino#30]
Hi. I'm trying to fine-tune a model on custom data. I have a few questions during the process, and it would be really helpful if you could answer them. Thank you in advance.

How is the dictionary called 'id_map' defined in `tools/coco2odvg.py?`
I don't understand how the id_map = {0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 14, 13: 15, 14: 16, 15: 17, 16: 18, 17: 19, 18: 20, 19: 21, 20: 22, 21: 23, 22: 24, 23: 25, 24: 27, 25: 28, 26: 31, 27: 32, 28: 33, 29: 34, 30: 35, 31: 36, 32: 37, 33: 38, 34: 39, 35: 40, 36: 41, 37: 42, 38: 43, 39: 44, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 55, 50: 56, 51: 57, 52: 58, 53: 59, 54: 60, 55: 61, 56: 62, 57: 63, 58: 64, 59: 65, 60: 67, 61: 70, 62: 72, 63: 73, 64: 74, 65: 75, 66: 76, 67: 77, 68: 78, 69: 79, 70: 80, 71: 81, 72: 82, 73: 84, 74: 85, 75: 86, 76: 87, 77: 88, 78: 89, 79: 90} is defined in the file.
- When using custom data, how should 'id_map' be defined?

If the val set in `config/datasets_mixed_odvg.json `is not coco, how should the 'label_map' be set in the json file? 
- If I define the label_list in `cfg_odvg.py`, is it okay to set the label_map in the json file to null?

Thank you🙌

**Comment by BIGBALLON** [comment]
1. The coco data set has 91 categories, but only 80 categories are used, so with this mapping relationship, the purpose is to sort from 0 to 79
2. Start from "0" (it is essential to start from 0 to accommodate caption/grounding data).
3. https://github.com/longzw1997/Open-GroundingDino/blob/main/data_format.md

**Comment by BIGBALLON** [comment]
When using custom data, how should 'id_map' be defined? check [v3det2odvg.py](https://github.com/longzw1997/Open-GroundingDino/blob/main/tools/v3det2odvg.py), this script is used for custom datasets in coco format.

**Comment by BIGBALLON** [comment]
> 1. The coco data set has 91 categories, but only 80 categories are used, so with this mapping relationship, the purpose is to sort from 0 to 79
> 2. Start from "0" (it is essential to start from 0 to accommodate caption/grounding data).
> 3. https://github.com/longzw1997/Open-GroundingDino/blob/main/data_format.md
> 4. If I define the label_list in cfg_odvg.py, is it okay to set the label_map in the json file to null? You need to check where it is used in the code and then replace it one by one. This is okay. How to use it depends entirely on how you modify the code.

![image](https://github.com/longzw1997/Open-GroundingDino/assets/7837172/75dc7729-9de1-4b4f-ad48-bab6901e1c0c)
