### ISSUE TITLE
Training-Data-Prep

### ISSUE THREAD

**Issue by Hasanmog** [longzw1997/Open-GroundingDino#31]
Hello , first of all thank you for releasing your training code!
I was trying to run it , but facing some issues in the format of my data.
I'm using a dataset which has its annotations in the form of PASCAL VOC ( each image has its own .xml annotation document).
So , I tried changing them to COCO format using this python script : [voc2coco.py](https://github.com/yukkyo/voc2coco/blob/master/voc2coco.py) , and then using your script coco2odvg tool.
but unfortunately , when generating the final odvg json file , I have an empty instances for all samples. 
examples:

This is after using coco2odvg :  
{"filename": "00003.jpg", "height": 800, "width": 800, "detection": {"instances": []}}
{"filename": "00004.jpg", "height": 800, "width": 800, "detection": {"instances": []}}

Thanks in advance :)

**Comment by BIGBALLON** [comment]
please check these issue， https://github.com/longzw1997/Open-GroundingDino/issues/19
，https://github.com/longzw1997/Open-GroundingDino/issues/15 ，https://github.com/longzw1997/Open-GroundingDino/issues/30

and you need create a new script for custom data format
