### ISSUE TITLE
The impact of the order of elements (i.e., text) within "cat_list" used in model evaluation

### ISSUE THREAD

**Issue by Leebh-kor** [longzw1997/Open-GroundingDino#32]
Thank you sincerely for sharing your training code. 🙌😥

I have a few questions while conducting evaluations on a model fine-tuned with custom object detection data.

In short, is there a definitive answer on how to structure `cat_lis`t for accurate model evaluation? Specifically, is there a correct order for the text elements within cat_list  (`i.e., label_list in cfg.py`)? **(The class mapping between the predictions of the model trained on the trainset and the validset has been correctly completed.)**

When evaluating a model fine-tuned on custom od data using another custom dataset, I observed that organizing `cat_list` based on the categories of the training set yields an mAP of approximately 0.45, whereas organizing it based on the categories of the validset yields a result of 0.15. (This pattern persists for different training sets with the same evaluation dataset.)

However, when using coco_val2017 for evaluation, I confirmed through the code that cat_list is organized based on the order of categories in the coco annotations (`e.g., cat_list = ['person', 'bicycle', ...]`). Furthermore, this `cat_list`, established in this manner, remains fixed and is utilized throughout the evaluation process.

Considering this process, it appears that the order of text elements in `cat_list `may not be crucial, is that correct? Alternatively, is organizing `cat_list` based on the categories of the validset a clear model evaluation method?

Thank you for reading the question, and I appreciate any insights you can provide.

**Comment by BIGBALLON** [comment]
1. Training and testing need to have the same ``cat_list``. It’s easy to understand if you treat it as traditional Object Detection task.
2. The order of text elements in cat_list may not be crucial, but be consistent,  just like traditional Object Detection, it depends on your anotations. 
3. Fine-tuning on OD datasets is not the main purpose, this will reduce the generalization ability of the model, and additional strategies need to be used to maintain generalization. https://github.com/longzw1997/Open-GroundingDino/issues/26
4. I don't think fine-tuning GDINO model will get the best performance(mAP, ACC, etc.) if you only want to detect object in **a closed set**(not a open-set), perhaps you can try some other networks(backbones)
