### ISSUE TITLE
pre-training

### ISSUE THREAD

**Issue by sheethalb** [longzw1997/Open-GroundingDino#38]
Hello ! thank you for your code. please could you help me understand if pre-training is possible with your code ? 

I have data in coco format, and i understand i need to convert to odvg format to use your code. but from what I understand, i still need the bbox annotations for the VG data as well, right? Is it possible to pre-train grounding dino with only the image-text pairs? 

thank you

**Comment by BIGBALLON** [comment]
Since [GLIP](https://github.com/microsoft/GLIP) unifies detection and grounding by reformulating object detection as **phrase grounding**, both VG and OD need bbox, Grounding Dino following GLIP's setting. So you can't pretrain Grounding Dino with only the image-text pairs?

**Comment by sheethalb** [comment]
thank you for your quick answer ! so if i have the bbox and the text for the grounding, I can use your implementation for the pre-training, is that right?

**Comment by BIGBALLON** [comment]
> thank you for your quick answer ! so if i have the bbox and the text for the grounding, I can use your implementation for the domain specific pre-training, is that right? thank you also to the link !

Yes. 



BTW, you can also refer to GLIP(3.3. Pre-training with Scalable Semantic-Rich Data) and OWL-V2(Scaling Open-Vocabulary Object Detection)

<img width="998" alt="image" src="https://github.com/longzw1997/Open-GroundingDino/assets/7837172/dd4d82ab-c5a1-424b-975d-80e194bc1431">
