### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'groundingdino' torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

### ISSUE THREAD

**Issue by FengheTan9** [longzw1997/Open-GroundingDino#4]
I'm running on a single A800：
 `bash train_dist.sh 1 config/cfg_coco.py config/datasets_od_example.json` 
![image](https://github.com/longzw1997/Open-GroundingDino/assets/54798078/a57b3cfd-cd63-4fbb-81de-95933e9e0d6a)

**Comment by FengheTan9** [comment]
new issue: DETR training and evaluation script: error: unrecognized arguments: --local-rank=0
![image](https://github.com/longzw1997/Open-GroundingDino/assets/54798078/3755a70e-8acd-4470-8bda-ec4f28dcb579)

**Comment by FengheTan9** [comment]
> I'm running on a single A800： `bash train_dist.sh 1 config/cfg_coco.py config/datasets_od_example.json` ![image](https://user-images.githubusercontent.com/54798078/275490490-a57b3cfd-cd63-4fbb-81de-95933e9e0d6a.png)

This issue has been solved by runing setup.py from the original groundingdino.

**Comment by longzw1997** [comment]
You can consider adding a local rank argument to the main function.

**Comment by nicholasprimiano** [comment]
You can also try running without the distributed pytorch stuff like this: 

!python /content/Open-GroundingDino/main.py \
        --output_dir ./logs \
        -c /content/Open-GroundingDino/config/cfg_odvg.py \
        --datasets /content/Open-GroundingDino/config/datasets_mixed_odvg.json  \
        --pretrain_model_path /content/Open-GroundingDino/groundingdino_swint_ogc.pth

This is on a colab notebook that I don't have 100% working yet but I did solve the local rank issue. Step by step instructions from the authors for  single GPU training would be helpful.

**Comment by BIGBALLON** [comment]
> > I'm running on a single A800： `bash train_dist.sh 1 config/cfg_coco.py config/datasets_od_example.json` ![image](https://user-images.githubusercontent.com/54798078/275490490-a57b3cfd-cd63-4fbb-81de-95933e9e0d6a.png)
> 
> This issue has been solved by runing setup.py from the original groundingdino.

This PR fixed this issue

https://github.com/longzw1997/Open-GroundingDino/pull/10
