### ISSUE TITLE
about train dataset questions

### ISSUE THREAD

**Issue by QzYER** [longzw1997/Open-GroundingDino#47]
There was an issue converting my local Coco dataset to a. jsoll file using the script you provided. My dataset is just one category.
I have made two modifications as follows:
![QQ图片20231222102850](https://github.com/longzw1997/Open-GroundingDino/assets/32487883/879638c2-6dcb-4c6f-8777-5dc9367a1437)
![QQ图片20231222102857](https://github.com/longzw1997/Open-GroundingDino/assets/32487883/89f33307-f86d-4331-80e7-3943a17f9684)

This is the information output after running the script：
![QQ图片20231222102903](https://github.com/longzw1997/Open-GroundingDino/assets/32487883/6a017a14-f4a6-493c-a402-1edad022ffa4)

The output log of the training process prompts the following issues:

![1703212340580](https://github.com/longzw1997/Open-GroundingDino/assets/32487883/390f8313-3ae1-4956-93c4-ef5844cee134)

Looking forward to your reply，thinks！

**Comment by BIGBALLON** [comment]
1. In dictionary form, indices start from "0" (it is essential to start from 0 to accommodate caption/grounding data). [Here](https://github.com/longzw1997/Open-GroundingDino/blob/main/config/coco2017_label_map.json) is an example
2. check https://github.com/longzw1997/Open-GroundingDino/blob/main/tools/v3det2odvg.py, which is the script that converts the coco format dataset to ogvd format.

**Comment by QzYER** [comment]
Thank you for your reply. May I ask if we will proceed with the Tensorrt acceleration work for GroundingDINO



---Original---
From: "WILL ***@***.***&gt;
Date: Sat, Dec 23, 2023 15:22 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [longzw1997/Open-GroundingDino] about train dataset questions(Issue #47)




  
In dictionary form, indices start from "0" (it is essential to start from 0 to accommodate caption/grounding data). Here is an example
 
check https://github.com/longzw1997/Open-GroundingDino/blob/main/tools/v3det2odvg.py, which is the script that converts the coco format dataset to ogvd format.

**Comment by BIGBALLON** [comment]
Maybe you need to contact the original author https://github.com/IDEA-Research/GroundingDINO

**Comment by abhimanyuchadha96** [comment]
@BIGBALLON What is the logic behind id_map being 
`'{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7}'# 7 classes of AquariumDataset`

Why isn't the mapping like
`{0: 0, 1: 1, 2: 2, 3: 4, 4: 4, 5: 5, 6: 6}`
