### ISSUE TITLE
could you share more details about converting ODVG dataformat?

### ISSUE THREAD

**Issue by SamXiaosheng** [longzw1997/Open-GroundingDino#50]
when reading the script of coco2odvg.py,but this file does not show that how to convert the VG dataformat only have OD dataformat.

**Comment by BIGBALLON** [comment]
- As long as your converted data file meets the ODVG data format, it will be fine. 
- As for the conversion code, you can write it yourself
- more: https://github.com/longzw1997/Open-GroundingDino/issues/19
