### ISSUE TITLE
Config for Swin-B training?

### ISSUE THREAD

**Issue by lanhas** [longzw1997/Open-GroundingDino#8]

**Comment by BIGBALLON** [comment]
1. change ``swin_T_224_1k`` to  ``swin_B_384_22k``
2. use the ckpt [groundingdino_swinb_cogcoor.pth](https://github.com/IDEA-Research/GroundingDINO/releases/download/v0.1.0-alpha2/groundingdino_swinb_cogcoor.pth) 

```
    [
        "swin_T_224_1k",
        "swin_B_224_22k",
        "swin_B_384_22k",
        "swin_L_224_22k",
        "swin_L_384_22k",
    ]:
```
