### ISSUE TITLE
Fine Tune on COCO

### ISSUE THREAD

**Issue by nicholasprimiano** [longzw1997/Open-GroundingDino#9]
I am attempting to get fine tuning on coco working before I use my own dataset.

I use the following command to run it in a colab notebook along with a truncated version of the output. Any thoughts on next steps for debugging:

'''
!python /content/Open-GroundingDino/main.py \
        --output_dir ./logs \
        -c /content/Open-GroundingDino/config/cfg_coco.py \
        --datasets /content/Open-GroundingDino/config/datasets_od_example.json  \
        --pretrain_model_path /content/Open-GroundingDino/groundingdino_swint_ogc.pth
'''

Not using distributed mode
Loading config file from /content/Open-GroundingDino/config/cfg_coco.py
INFO     2023-10-18 17:57:30,403 | git:
  sha: 9036724fad8d71ca1234e869da47bed0157d0fa0, status: has uncommited changes, branch: main
INFO     2023-10-18 17:57:30,403 | Command: /content/Open-GroundingDino/main.py --output_dir ./logs -c /content/Open-GroundingDino/config/cfg_coco.py --datasets /content/Open-GroundingDino/config/datasets_od_example.json --pretrain_model_path /content/Open-GroundingDino/groundingdino_swint_ogc.pth
INFO     2023-10-18 17:57:30,404 | Full config saved to ./logs/config_args_all.json
INFO     2023-10-18 17:57:30,405 | world size: 1
INFO     2023-10-18 17:57:30,405 | rank: 0
INFO     2023-10-18 17:57:30,405 | local_rank: 0
........
DEBUG    2023-10-18 17:57:30,406 | build model ... ...
/content/Open-GroundingDino/models/GroundingDINO/ms_deform_attn.py:31: UserWarning: Failed to load custom C++ ops. Running on CPU mode Only!
  warnings.warn("Failed to load custom C++ ops. Running on CPU mode Only!")
/usr/local/lib/python3.10/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
final text_encoder_type: bert-base-uncased
load tokenizer done.
........
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py:905: FutureWarning: The `device` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Traceback (most recent call last):
  File "/content/Open-GroundingDino/main.py", line 371, in <module>
    main(args)
  File "/content/Open-GroundingDino/main.py", line 284, in main
    train_stats = train_one_epoch(
  File "/content/Open-GroundingDino/engine.py", line 47, in train_one_epoch
    outputs = model(samples, captions=captions)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/Open-GroundingDino/models/GroundingDINO/groundingdino.py", line 315, in forward
    hs, reference, hs_enc, ref_enc, init_box_proposal = self.transformer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/Open-GroundingDino/models/GroundingDINO/transformer.py", line 258, in forward
    memory, memory_text = self.encoder(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/Open-GroundingDino/models/GroundingDINO/transformer.py", line 580, in forward
    output = checkpoint.checkpoint(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/Open-GroundingDino/models/GroundingDINO/transformer.py", line 793, in forward
    src2 = self.self_attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/Open-GroundingDino/models/GroundingDINO/ms_deform_attn.py", line 338, in forward
    output = MultiScaleDeformableAttnFunction.apply(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/content/Open-GroundingDino/models/GroundingDINO/ms_deform_attn.py", line 53, in forward
    output = _C.ms_deform_attn_forward(
NameError: name '_C' is not defined

**Comment by nicholasprimiano** [comment]
I see two main issues: 

1. "/content/Open-GroundingDino/models/GroundingDINO/ms_deform_attn.py:31: UserWarning: Failed to load custom C++ ops. Running on CPU mode Only!
  warnings.warn("Failed to load custom C++ ops. Running on CPU mode Only!")" 

2. "NameError: name '_C' is not defined" which is possibly related to a cuda issue per the official grounding dino github

**Comment by BIGBALLON** [comment]
> I see two main issues:
> 
> 1. "/content/Open-GroundingDino/models/GroundingDINO/ms_deform_attn.py:31: UserWarning: Failed to load custom C++ ops. Running on CPU mode Only!
>    warnings.warn("Failed to load custom C++ ops. Running on CPU mode Only!")"
> 2. "NameError: name '_C' is not defined" which is possibly related to a cuda issue per the official grounding dino github

Hi, @nicholasprimiano 
- I think this may be caused by the CUDA operator not being compiled correctly.
- Is it possible to compile the operator before executing it in colab?
- https://github.com/longzw1997/Open-GroundingDino/issues/7

**Comment by BIGBALLON** [comment]
This PR fixed this issue

https://github.com/longzw1997/Open-GroundingDino/pull/10

**Comment by lanhas** [comment]
For the following problems:
    1. UserWarning: Failed to load custom C++ ops. Running on CPU mode Only!
    2."NameError: name '_C' is not defined"
I solved this by installing groundingdino-0.1.0 via the official code for [Grounding-DINO](https://github.com/IDEA-Research/GroundingDINO).

I found that "ms_deform_attn.py" contains "from groundingdino import_C ", but groundingdino is not installed.

**Comment by BIGBALLON** [comment]
@lanhas
> I found that "ms_deform_attn.py" contains "from groundingdino import_C ", but groundingdino is not installed.

This PR fixed your issue https://github.com/longzw1997/Open-GroundingDino/pull/10 by change 
"from groundingdino import_C " to "import MultiScaleDeformableAttention as _C"

**Comment by lanhas** [comment]
> @lanhas
> 
> > I found that "ms_deform_attn.py" contains "from groundingdino import_C ", but groundingdino is not installed.
> 
> This PR fixed your issue #10 by change "from groundingdino import_C " to "import MultiScaleDeformableAttention as _C"

Oops, you updated the code of "ms_deform_attn.py", I still use the previous version.
