### ISSUE TITLE
有关预训练的问题

### ISSUE THREAD

**Issue by lxiaohaung** [longzw1997/Open-GroundingDino#93]
在pretrain的时候，在算loss的时候会有一个box格式的转变，从xwwh到x1y1x2y2的转变，这里面有一个对x2>x1,y2>y1的assert，但是我预训练的时候，wh有时候会是负的，想问问您有这个问题吗

**Comment by LuletterSoul** [comment]
你好，你解决这个问题了么

**Comment by lxiaohaung** [comment]
已经解决了

**Comment by LuletterSoul** [comment]
> 已经解决了

请问怎么解决的，感谢，我也遇到这个问题

**Comment by lxiaohaung** [comment]
我当时的问题不是负的，是有时候会报None，我记得是因为在某个程序里softmax之后会出问题，给加了个小量就好了

**Comment by LuletterSoul** [comment]
> 我当时的问题不是负的，是有时候会报None，我记得是因为在某个程序里softmax之后会出问题，给加了个小量就好了

可以列出更详细的解决方法么，搜索了全局的softmax用到的地方其实不多
